# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  docker,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0c9wrp0393sg25s49kk10bjgc05rxi07jpa263dzp8fm7kj6fsmk";
    aarch64-linux = "1q7r8mi44a33qkn20vprpgbz6q068ipr80iixxlfilqm9xbawpqa";
    x86_64-darwin = "1zh260h4i3jl09habk1y41ijhcpqi4a251gk3j9yvs9af7sy04f7";
    aarch64-darwin = "18n5miyzj81fpfxvv2japnvipksb1ij7f839dahrcf5i91fxv4kk";
  };

  urlMap = {
    x86_64-linux = "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dxup";
  version = "0.18.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dxup $out/bin/dxup
    installManPage ./docs/man/*.1
    installShellCompletion ./docs/completions/*
  '';

  meta = {
    description = "Reproducible development environments with Docker and Nix";
    homepage = "https://github.com/dxupsh/dxup";
    license = lib.licenses.agpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
